name: Publish to npm



on:
  push:
    tags:
      - v/*



jobs:

  publish-npm:

    runs-on: ubuntu-slim
    timeout-minutes: 3

    permissions:
      contents: read
      id-token: write

    steps:

      - name: Setup repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: v24
          registry-url: https://registry.npmjs.org/

      - name: Move package.json
        run: |-

          VER=$(jq -r '.version' deno.json)
          sed "s/0.0.0-VERSION/$VER/" tmp-package.json > package.json

      - name: Install
        run: npm install --no-{fund,package-lock}

      - name: Build
        run: npx tsc ./src/*.ts
                     --outDir ./dist
                     --types  node
                     --lib    es2023
                     --target es2023
                     --module preserve
                     --strict
                     --isolatedModules
                     --erasableSyntaxOnly
                     --rewriteRelativeImportExtensions

      - name: Publish (latest)
        if: contains(github.ref_name, '-') == false
        run: npm publish --access=public --tag=latest

      - name: Publish (next)
        if: contains(github.ref_name, '-') == true
        run: npm publish --access=public --tag=next

